### PR TITLE
Fixes #199 Swift 4.1 support

### LINKED ISSUE #199: With Swift 4.1 is broken

### PR DESCRIPTION
**Pull request by fassko**

### CODE REVIEW

File: QminderAPITests/APITests/DevicesAPITests.swift [hunk 1]
```diff
@@ -43,7 +43,7 @@ class DevicesAPITests: QminderAPITests {
   }
   
   func testPairTV() {
-    var e: Error?
```
Comment (2ndalpha) [inline QminderAPITests/APITests/DevicesAPITests.swift]: This has nothing to do with Swift 4.1, right? Just cosmetic?

**Comment by fassko** [comment]
Swiftlint complained. I think it’s because Sourcekit was updated as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
